"""removed for rent on properties, added created at on user & properties

Revision ID: 2c93d75971f3
Revises: 1123c585d9a4
Create Date: 2024-06-29 17:02:52.563004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c93d75971f3'
down_revision = '1123c585d9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('for_rent')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_rent', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
