"""added followers join table and redefined relationships

Revision ID: 3330e22cfaac
Revises: 17afc6153fe2
Create Date: 2024-05-17 11:35:06.090200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3330e22cfaac'
down_revision = '17afc6153fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('following')
        batch_op.drop_column('followers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('following', sa.INTEGER(), nullable=True))

    op.drop_table('followers')
    # ### end Alembic commands ###
