"""added table for follow and followers

Revision ID: 699c16fc380e
Revises: aa416221c588
Create Date: 2024-06-16 00:09:00.793923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699c16fc380e'
down_revision = 'aa416221c588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
