"""added rooms to property model

Revision ID: 736fee63c7e1
Revises: 707c10466888
Create Date: 2024-04-28 02:04:23.038249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736fee63c7e1'
down_revision = '707c10466888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rooms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('rooms')

    # ### end Alembic commands ###
