"""addedwifi, gated, hot-shower, kitchen, balcony, parking fields on the properties table

Revision ID: 73bda8ca7788
Revises: 9e52626f342b
Create Date: 2024-05-04 22:38:33.386556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bda8ca7788'
down_revision = '9e52626f342b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wifi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hot_shower', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('kitchen', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('balcony', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parking', sa.Boolean(), nullable=True))
        batch_op.drop_column('compatibility_factors')
        batch_op.drop_column('amenities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenities', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('compatibility_factors', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('parking')
        batch_op.drop_column('balcony')
        batch_op.drop_column('kitchen')
        batch_op.drop_column('hot_shower')
        batch_op.drop_column('gated')
        batch_op.drop_column('wifi')

    # ### end Alembic commands ###
