"""added availability column on the property model

Revision ID: 804b7de256b8
Revises: 73bda8ca7788
Create Date: 2024-05-05 01:23:23.147117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804b7de256b8'
down_revision = '73bda8ca7788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('available')

    # ### end Alembic commands ###
