"""added for_rent field on the properties table

Revision ID: 9e52626f342b
Revises: 736fee63c7e1
Create Date: 2024-05-04 21:01:24.603629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e52626f342b'
down_revision = '736fee63c7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_rent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('for_rent')

    # ### end Alembic commands ###
