"""added unique constraints to the join table

Revision ID: c790a581ae39
Revises: 3330e22cfaac
Create Date: 2024-05-17 12:30:46.983223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c790a581ae39'
down_revision = '3330e22cfaac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_follow_pair', ['follower_id', 'followed_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint('unique_follow_pair', type_='unique')

    # ### end Alembic commands ###
